databases:
  - name: components-database-2024
    region: frankfurt
    plan: starter
    ipAllowList: [] # only allow internal connections

services:
  - type: web
    name: components-web
    region: frankfurt
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate && bundle exec rails db:seed"
    startCommand: "bundle exec rails server"
    domains:
     - 'components.oxteam.me'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: components-database-2024
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: oxteam-cache
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2
      - fromGroup: components-settings
      - fromGroup: oxteam-settings

envVarGroups:
  - name: components-settings
    envVars:
      - key: RAILS_MASTER_KEY # for production installs uncomment this line
        sync: false # for production installs uncomment this line
      - key: ADMIN_EMAIL
        value: 'spree@example.com'
      - key: ADMIN_PASSWORD
        value: 'spree123'
      - key: AUTO_ACCEPT
        value: 'true'
