databases:
  - name: components-database-2024
    region: frankfurt
    plan: starter
    ipAllowList: [] # only allow internal connections

services:
  - type: worker
    name: components-worker
    region: frankfurt
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rake solid_queue:start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: components-database-2024
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: oxteam-cache
          property: connectionString
      - fromGroup: components-settings
      - fromGroup: oxteam-settings
  - type: web
    name: components-web
    region: frankfurt
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate && bundle exec rails db:seed"
    startCommand: "bundle exec rails server"
    healthCheckPath: /up
    domains:
     - 'components.oxteam.me'
     - 'smart-components.store'
     - 'smart-components.pro'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: components-database-2024
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: oxteam-cache
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 1
      - key: RAILS_MAX_THREADS
        value: 1
      - fromGroup: components-settings
      - fromGroup: oxteam-settings

envVarGroups:
  - name: components-settings
    envVars:
      - key: RAILS_MASTER_KEY # for production installs uncomment this line
        sync: false # for production installs uncomment this line
