default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 10
  workers:
    - queues: "*"
      threads: 1
      processes: 1
      polling_interval: 1.0

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
